### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'db')

### ISSUE THREAD

**Issue by Chinesename** [localForage/localForage#1101]
my code :
`import localforage from "localforage";
export const db_upload = localforage.createInstance({ name: "test", storeName: "upload" });`
error：
`TypeError: Cannot read properties of null (reading 'db')
    at _tryReconnect (localforage.js:770:1)
    at localforage.js:819:1`

The localforage did not initialize successfully, causing instance creation to fail. How can we ensure that the localforage is initialized successfully before creating an instance.

**Comment by rap2hpoutre** [comment]
Up

**Comment by Sr-santi** [comment]
@Chinesename, are you using React or what?
Can you provide more context?

**Comment by Sr-santi** [comment]
this project is no longer maintained. 
I talked to the main contributor, he told me that he will archive this repo eventually.
