### ISSUE TITLE
IE8: Object doesn't support this property or method

### ISSUE THREAD

**Issue by jussi-kalliokoski** [localForage/localForage#220]
Unfortunately it looks like the fix for the property names was not enough to fix IE8. Calling any localforage method (I tried `setItem`, `getItem` and `clear`) results in an error `Object doesn't support this property or method`. I think it would be worthwhile spending time on getting the test suite running on some cross-browser cloud testing provider. This is an open source project so getting a free account should be easy (I myself just made an account and contacted their customer support asking to activate the open source plan). Saucelabs is also free for open source.

Having had my own tests run in the cloud for a suite of browsers for every PR has at least made me feel much more confident about making changes, so I highly recommend. :) I can also do my best to help if you have questions, but my previous setups have been quite homogenous and different from yours (gulp, karma, mocha, expect.js), so my knowledge will probably only be partially applicable here.

**Comment by Irrelon** [comment]
There is also an issue with the source in src/localforage.js (and subfolders/files) but not in the dist/localforage.js which is that in source there is a lot of use of:

    .catch(reject)

This is presented as:

    ["catch"](reject)

In the dist folder files. If you run browserify and require localforage you end up with a build that IE8 doesn't like because it complains about the .catch(reject) lines. I'm happy to do a PR to fix this in the src folder but wasn't sure if it would break something since it appears you guys already have a conversion in place because the dist folder files don't show the same code?

**Comment by thgreasi** [comment]
@Irrelon I think you should only use the dist files in your project, no
matter how you are loading them ( script tag/ require js/ browserify ).
You can surely use the src files directly, but then you should also
introduce all the build steps that are used in the repo to your build task,
if you care about ie8.

Moreover, there is also #158. So, when some of the library's code is
converted to es6, then many browser ( besides ie8 ) will be broken if
someone still uses the src files.

**Comment by tofumatt** [comment]
Yeah, I would hope browserify is still using the `dist/` versions of the files, right? If not that's a separate bug that relates to this, but if the `dist/` versions are what is told to be used then this bug might be a "won't fix" under "don't use the `src/` files directly in-browser".

**Comment by Irrelon** [comment]
Browserify is using the src files as far as I can tell. I'm going to do a quick test to make absolutely sure it's not user error (as in me being stupid :p).

**Comment by Irrelon** [comment]
Confirmed that browserify is DEFINITELY using the src files. In the package.json there is a "browser" key pointing to the src/localforage.js file. If you comment this out so that browserify uses the "main" key instead (pointing to dist/localforage.js) then browserify will fail with the error:

```
Error: Cannot find module './../utils/serializer' from '/Development/ForerunnerDB/node_modules/localforage/dist'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:42:25
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)
```

This stops anything generated with browserify from working in IE8 because of the above issues around "catch" etc.

**Comment by tofumatt** [comment]
Curious, we are using an es3-safe task that should [make things okay for IE 8](https://github.com/mozilla/localForage/blob/master/dist/localforage.js#L1001).

**Comment by tofumatt** [comment]
Oh, wait, I understand why: it tries to import that module that's already in the `dist` file that's combined.

There are a few options here I guess. Could we supply a `dist/browserify` folder (messy, but could keep our `src/` files clean) that is es3-safe but uses separate files?

I don't REALLY care what `dist/` looks like that much, especially when we specify `dist/localforage.js` as the default. Building out a folder for browserify, which is a big thing for lots of developers, is fine by me.

**Comment by Irrelon** [comment]
@tofumatt Sounds like it might be the answer... it would be good to be able to select the non-promise version (optionally) via browserify as well. I've noticed that if I run unit tests via a browser they pass fine (for my project ForerunnerDB) but if I run them through phantomjs I get an error related to localforage:

    TypeError: 'undefined' is not a function (evaluating 'then.bind(newValue)')

I have no idea why this works on a browser but not in phantom.

**Comment by psalaets** [comment]
@Irrelon I think you're running into ariya/phantomjs#10522, which is fixed for phantom 2

**Comment by andela-idurotola** [comment]
karma unit test fails. it says " Can't find variable: require". i am using the bower version of localforage
'''
![screen shot 2015-03-25 at 9 31 24 am](https://cloud.githubusercontent.com/assets/8592741/6820654/81d40f4c-d2d1-11e4-97ad-c0204ff8e506.png)

**Comment by tofumatt** [comment]
Oh, weird, are there still karma unit tests? I think I experimented with them but should have removed them.

To run tests try `npm test`. I’ll remove the karma files. :-)

**Comment by andela-idurotola** [comment]
thanks i have fixed it. i figured require must have been redefined by some
of the other loaded files so i moved it up

*Durotola Iyanu Tomiwa | Software Developer | Andela*
Tel: 0706-671-9488 | Andela.co <http://andela.co/> | @ThisIsAndela
<http://twitter.com/ThisIsAndela>
Face your Fears.......

**Comment by thgreasi** [comment]
Just tested the dist build on IE8 emulaton (within IE11) and everything worked fine.
Should this be closed?

**Comment by Irrelon** [comment]
@thgreasi I found the issue was present when including localforage using browserify because the post-process stage that gets run when generating the dist build for this repo is not executed when using browserify. The issue cannot therefore be checked by testing the dist build but rather by building with browserify in a separate project and then testing it.

**Comment by thgreasi** [comment]
[Here is how we polyfill Promises in our browserify test case in the v1.2 branch](https://github.com/mozilla/localForage/blob/pre-es6-refactor/test/runner.browserify.js#L1-L3).
It is actually equivalent to what you propose
Since browserify is pointed to the src files, it's currently like you are including the nopromises dist file.
What is the exact error that you get?

This should be fixed in v1.3 .

**Comment by thgreasi** [comment]
Ok forget everything I told about the promises. Just now I realized that you were talking about the es3 step.

**Comment by thgreasi** [comment]
Regardless, this should work in v1.3 :)
