### ISSUE TITLE
Reinitialize IndexedDb if cleared during runtime

### ISSUE THREAD

**Issue by ccorcos** [localForage/localForage#732]

**Comment by thgreasi** [comment]
Can you try using #708? which adds dropInstance() and reinitializes the db after an instance is dropped.

**Comment by bhaidar** [comment]
Hello @thgreasi 
Is this error related to this issue?

````ERROR DOMException: Failed to execute 'put' on 'IDBObjectStore': function (number) {
        var b = number % 10,
            output = (toInt(number % 100 / 10) === 1) ? 'th' :...<omitted>... } could not be cloned.
    at http://localhost:4200/vendor.bundle.js:10127:29
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:7073:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:136945:33)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:7072:32)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (http://localhost:4200/polyfills.bundle.js:6833:43)
    at http://localhost:4200/polyfills.bundle.js:7466:57
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:7106:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:136936:33)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:7105:36)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost:4200/polyfills.bundle.js:6873:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:7299:35)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:7172:25)`````

**Comment by thgreasi** [comment]
@bhaidar I can't identify something relevant in your stack trace, so my guess is no.

**Comment by bhaidar** [comment]
@thgreasi I understand. Thank you.
Actually, I am using this code, maybe the problem is from this.
https://www.cloudspecialist.uk/2017/04/25/Caching-RxJS-Http-Observables-offline-in-an-Angular-2-application/

**Comment by bhaidar** [comment]
@thgreasi 
But wait, isn't this the code in the library?

````
function setItem(key, value, callback) {
    var self = this;

    // Cast the key to a string, as that's all we can set as a key.
    if (typeof key !== 'string') {
        console.warn(key + ' used as a key, but it is not a string.');
        key = String(key);
    }

    var promise = new Promise$1(function (resolve, reject) {
        var dbInfo;
        self.ready().then(function () {
            dbInfo = self._dbInfo;
            if (toString.call(value) === '[object Blob]') {
                return _checkBlobSupport(dbInfo.db).then(function (blobSupport) {
                    if (blobSupport) {
                        return value;
                    }
                    return _encodeBlob(value);
                });
            }
            return value;
        }).then(function (value) {
            var transaction = dbInfo.db.transaction(dbInfo.storeName, 'readwrite');
            var store = transaction.objectStore(dbInfo.storeName);
            var req = store.put(value, key);

            // The reason we don't _save_ null is because IE 10 does
            // not support saving the `null` type in IndexedDB. How
            // ironic, given the bug below!
            // See: https://github.com/mozilla/localForage/issues/161
            if (value === null) {
                value = undefined;
            }

            transaction.oncomplete = function () {
                // Cast to undefined so the value passed to
                // callback/promise is the same as what one would get out
                // of `getItem()` later. This leads to some weirdness
                // (setItem('foo', undefined) will return `null`), but
                // it's not my fault localStorage is our baseline and that
                // it's weird.
                if (value === undefined) {
                    value = null;
                }

                resolve(value);
            };
            transaction.onabort = transaction.onerror = function () {
                var err = req.error ? req.error : req.transaction.error;
                reject(err);
            };
        })["catch"](reject);
    });

    executeCallback(promise, callback);
    return promise;
}
````

The exception is thrown here:

````
var req = store.put(value, key);
````

**Comment by thgreasi** [comment]
Oh, this wasn't shown in the stack trace though. Can you also post the error message itself that the promise is rejected with?

**Comment by bhaidar** [comment]
@thgreasi 
What message specifically?

**Comment by thgreasi** [comment]
The one that the `setItem` promise is rejected with.

**Comment by bhaidar** [comment]
Isn't the one I posted above? Anything else I should look at?

**Comment by bhaidar** [comment]
@thgreasi It seems Im not able to catch the exception. Can you please guide me where shall i put the breakpoint to capture that exception?

**Comment by thgreasi** [comment]
There isn't a good place to add a breakpoint in the above code. You should add a `.catch()` in the piece of code that invokes `setItem()` and get the error from there.

**Comment by bhaidar** [comment]
@thgreasi 
No error is thrown there!

I got this from the browser developer tool. I dunno if they help:

![image](https://user-images.githubusercontent.com/1163421/30328292-904bea86-97d7-11e7-96e0-aef517008aad.png)

**Comment by bhaidar** [comment]
By the way, storing pure string works fine without any errors.
What I am saving is an object which has a set of properties of Arrays. Is that a problem?

**Comment by bhaidar** [comment]
Hi @thgreasi again.
I am doing some tests around. It seems one of the properties to this object I am receiving from server, I have added recently is causing the problem. The property is an array of few objects, each object has a total of 14 properties. Do you think this is the reason behind this error? If I remove this property from server, all works well. I try to minimize the number of properties returned on that array of objects and also it works. Is there a limit on the number of properties per object?

**Comment by thgreasi** [comment]
This souldn't happen.
I would love to get a sample JSON of your object or even better a fork of [this codepen example](https://codepen.io/thgreasi/pen/ojYKeE) demonstrating the issue.
Thanks for elaborating on this, even though I've started thinking that this should better be in a separate issue.

**Comment by bhaidar** [comment]
Hello @thgreasi  I will start a new issue. sorry for that.

**Comment by thgreasi** [comment]
@ccorcos any feedback on this?

**Comment by ccorcos** [comment]
Hey sorry, busy week. I think the problem is that the database is only created when the window loads. This isn't a very big issue because the user just has to refresh, but it does feel like its not as resilient as it could be:

```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```

**Comment by thgreasi** [comment]
Hey @ccorcos thanks for thinking some time to elaborate on this 
Can you reply to my earlier inquiry:
> Can you try using #708? which adds dropInstance() and reinitializes the db after an instance is dropped.

**Comment by thgreasi** [comment]
@ccorcos The `dropInstance()` PR in in the current master (and planned to be released as LF v1.6) can you give it a try? It should fix your issue.
