### ISSUE TITLE
how to use with npm ?

### ISSUE THREAD

**Issue by ctf0** [localForage/localForage#778]
i tried using
```js
window.localforage = require('localforage')
```
but got tons of missing dependencies. 

then i've tried
```js
window.localforage = require('script!localforage')
```
but i get the error `Module not found: Error: Can't resolve 'script'` but `script-loader` is actually installed with **v0.7.2**

however downloading it manually and including it 
```js
window.localforage = require('./path/to/localforage.min.js')
```
works without any issues, but this ain't a good solution

so how exactly can we install it using npm ?

**Comment by tofumatt** [comment]
I don't understand, I use localforage in my `package.json` and do `import localforage from 'localforage';` without issue. Are you running `npm install`?

Could you post the exact error message you're getting when trying to `require('localforage')`?

**Comment by ctf0** [comment]
when using `import localforage from 'localforage'; ` or `window.localforage = require('localforage')`

```
ERROR in ./node_modules/localforage/dist/localforage.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/novo/Public/www/_testing/five/node_modules/localforage/.babelrc" at 0, attempted to resolve relative to "/Users/novo/Public/www/_testing/five/node_modules/localforage"
    at /Users/novo/Public/www/_testing/five/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/novo/Public/www/_testing/five/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/novo/Public/www/_testing/five/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/novo/Public/www/_testing/five/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/novo/Public/www/_testing/five/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/novo/Public/www/_testing/five/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/novo/Public/www/_testing/five/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/novo/Public/www/_testing/five/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/novo/Public/www/_testing/five/node_modules/babel-loader/lib/index.js:175:20)
```

installing `add-module-exports` preset will lead into another error afterwards.

**Comment by tofumatt** [comment]
What happens if you remove your `.babelrc` file? From the error message it looks like that’s the cause of the error, not localForage.

**Comment by ctf0** [comment]
actually the `.babelrc` is inside the `localforage` folder
> /testing/node_modules/localforage/.babelrc

not mine

**Comment by tofumatt** [comment]
Oh, weird, right.

It’s strange because we haven’t run into such an issue on addons-frontend, where we use it. Is there any chance you could submit a zip of the project to try, for debugging? I’ve never seen this error before.

**Comment by ctf0** [comment]
found the problem, i've this in webpack config

```js
module: {
        rules: [
            {
                test: /\.jsx?$/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['env', 'stage-3']
                    }
                }
            }
        ]
    }
```

can we get around that with lf ?

**Comment by tofumatt** [comment]
What does that preset do? Sorry I’m not familiar with that Babel config so not sure what it’s changing for localForage. :-)

**Comment by ctf0** [comment]
this is just a preset same as the one LF use, that tells babel how to compile the es6 stuff to plain js

its not related to LF, but i need it for another package to work :cry:
